# Dependencies
markdown: kramdown
kramdown:
    input: GFM

highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: DISsecT
tagline: "CTU Hacking team"
description: "Hacking Team at Czech Technical University. Patronaged by Department of Information Security at Faculty of Information Technology."
url: https://dissect.eu
baseurl: /

author:
    name: "DISsecT team"

paginate: 10
paginate_path: "/blog/page:num/"

plugins:
    - jekyll-paginate

# https://github.com/github/pages-gem/issues/399
github: [metadata]

# Separator of post overview displayed on home page, default is first paragraph
excerpt_separator: "<!--more-->"

exclude:
    - CNAME
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE.md
    - README.md
