# Dependencies
markdown:         kramdown
kramdown:
  input: GFM
  
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            DISsecT
tagline:          'A Jekyll theme'
description:      'Hacking Team at Czech Technical University. Patronaeged by Department of Information Security at Faculty of Information Technology'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
        - jekyll-paginate
        - jekyll-gist
        - redcarpet
