# Dependencies
markdown: kramdown
kramdown:
  input: GFM

highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: DISsecT
tagline: "CTU Hacking team"
description: "Hacking Team at Czech Technical University. Patronaged by Department of Information Security at Faculty of Information Technology"
url: https://dissect.eu
baseurl: /

author:
  name: "DISsecT team"

paginate: 5

# Custom vars
version: 2.1.0

plugins:
  - jekyll-paginate
  # - jekyll-gist
  # - redcarpet

# https://github.com/github/pages-gem/issues/399
github: [metadata]

# Separator of post overview displayed on home page, default is first paragraph
excerpt_separator: "<!--more-->"
