jekyll:
    # image: jekyll/jekyll:pages
    image: jekyll/jekyll
    command: jekyll serve --livereload
    ports:
        - 4000:4000
        - 35729:35729  # for loading the livereload javascript file
    volumes:
        - .:/srv/jekyll
